services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
        POSTGRES_DB: ${POSTGRES_DB:-postgres}
        POSTGRES_USER: ${POSTGRES_USER:-postgres}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"